version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-test-6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-test-6:/data/db
    command: --wiredTigerCacheSizeGB 1.5
  top_api:
    image: top-api:latest
    container_name: top_api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env/opt/app/.env